# ===============================
# Dependencies
# ===============================
FROM node:24-alpine AS deps

WORKDIR /app

COPY package*.json ./

RUN npm ci


# ===============================
# Builder
# ===============================
FROM node:24-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

RUN npm run build


# ===============================
# Production
# ===============================
FROM node:24-alpine

ENV NODE_ENV=production

WORKDIR /app

RUN addgroup -S app && \
    adduser -S app -G app

COPY --from=builder /app/public ./public

COPY --from=builder /app/.next/standalone ./

COPY --from=builder /app/.next/static ./.next/static

USER app

EXPOSE 3000

CMD ["node", "server.js"]